"""enforce global uniqueness on username and email

Revision ID: 0f81d6f4c0a5
Revises: 6c31ff191a99
Create Date: 2026-02-16 01:13:37.373318

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f81d6f4c0a5"
down_revision: Union[str, Sequence[str], None] = "6c31ff191a99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=150), nullable=True
    )
    op.drop_constraint(op.f("uq_user_tenant_email"), "users", type_="unique")
    op.drop_constraint(op.f("uq_user_tenant_username"), "users", type_="unique")
    op.create_unique_constraint("uq_user_email", "users", ["email"])
    op.create_unique_constraint("uq_user_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_username", "users", type_="unique")
    op.drop_constraint("uq_user_email", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_user_tenant_username"),
        "users",
        ["tenant_id", "username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_user_tenant_email"),
        "users",
        ["tenant_id", "email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=150), nullable=False
    )
    # ### end Alembic commands ###
