"""softdelete migration

Revision ID: 6c31ff191a99
Revises: b758ab9d7e02
Create Date: 2026-02-15 01:24:38.241639

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c31ff191a99"
down_revision: Union[str, Sequence[str], None] = "b758ab9d7e02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("comments", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "comments", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "invitations",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("invitations", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "invitations", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "leaves", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("leaves", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "leaves", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "tasks", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tasks", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "tasks", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "tenants", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tenants", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "tenants", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "users", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "deleted_by")
    op.drop_column("users", "deleted_at")
    op.drop_constraint(None, "tenants", type_="foreignkey")
    op.drop_column("tenants", "deleted_by")
    op.drop_column("tenants", "deleted_at")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "deleted_by")
    op.drop_column("tasks", "deleted_at")
    op.drop_constraint(None, "leaves", type_="foreignkey")
    op.drop_column("leaves", "deleted_by")
    op.drop_column("leaves", "deleted_at")
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.drop_column("invitations", "deleted_by")
    op.drop_column("invitations", "deleted_at")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "deleted_by")
    op.drop_column("comments", "deleted_at")
    # ### end Alembic commands ###
